name: jose2
description: Javascript Object Signing and Encryption (JOSE) library supporting JWE, JWS, JWK and JWT
version: 0.3.4
repository: https://github.com/heacare/jose

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  meta: ^1.1.6
  typed_data: ^1.0.0
  x509: ^0.2.1
  http: ^0.13.0
  http_parser: ^4.0.0
  asn1lib: ^1.0.0
  collection: ^1.15.0
    
dependency_overrides:
  crypto_keys:
    git:
      url: https://github.com/muhammadsaddamnur/crypto_keys.git
      ref: master 

dev_dependencies:
  test: ^1.0.0
  lints: ^2.0.0

false_secrets:
- test/pem/*.key
- example/*.key
- example/*.key.pub
